#ifndef CONSTANT_H
#define CONSTANT_H

#define WINDOW_WIDTH 1500
#define WINDOW_HEIGHT 750
#define BUS_WINDOW_WIDTH 1500
#define BUS_WINDOW_HEIGHT 1000

#define IMG_WIDTH 996
#define IMG_HEIGHT 647
#define BUSIMG_WIDTH 1135
#define BUSIMG_HEIGHT 765

#define NO_EXISTED_NUM 0
#define SUCCESS_FOUND 1

#define SCENIC_NUM 7
#define SCENIC_RECT_SIZE 8

#define CHINESE_HALL 1
#define BOTANICAL_HALL 2
#define GARDENING_TOWN 3
#define YONGNING_PAVILION 4
#define GUIRUI_THEATRE 5
#define INTERNATIONAL_HALL 6
#define LIFE_EXPERIENCE_HALL 7

const int inf = 0x3f3f3f3f;
#endif // CONSTANT_H
